
export const exampleProducts = [
    {
        id: "prod_1",
        name: "Organic Red Tomatoes",
        description: "Fresh, juicy, and organically grown tomatoes, perfect for salads and sauces. Straight from the farm.",
        category: "Vegetables",
        price: 2.50,
        farmer_id: "farmer_mock_1",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_1/400/300",
    },
    {
        id: "prod_2",
        name: "Himalayan Apples",
        description: "Crisp and sweet apples from the Himalayan foothills. A healthy and delicious snack.",
        category: "Fruits",
        price: 3.00,
        farmer_id: "farmer_mock_2",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_2/400/300",
    },
    {
        id: "prod_3",
        name: "Basmati Rice (1kg)",
        description: "Premium quality long-grain Basmati rice, known for its aroma and fluffy texture.",
        category: "Grains",
        price: 5.00,
        farmer_id: "farmer_mock_3",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_3/400/300",
    },
    {
        id: "prod_4",
        name: "Farm-Fresh Carrots",
        description: "Sweet and crunchy carrots, rich in vitamins. Ideal for cooking and snacking.",
        category: "Vegetables",
        price: 1.80,
        farmer_id: "farmer_mock_1",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_4/400/300",
    },
    {
        id: "prod_5",
        name: "Organic Spinach",
        description: "Tender and nutrient-packed spinach leaves. Great for salads, smoothies, and curries.",
        category: "Leafy Greens",
        price: 2.20,
        farmer_id: "farmer_mock_4",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_5/400/300",
    },
    {
        id: "prod_6",
        name: "Alphonso Mangoes",
        description: "The king of mangoes, known for its rich flavor and sweet aroma. A seasonal delight.",
        category: "Fruits",
        price: 8.50,
        farmer_id: "farmer_mock_2",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_6/400/300",
    },
    {
        id: "prod_7",
        name: "Whole Wheat Flour (1kg)",
        description: "Freshly milled whole wheat flour (atta), perfect for making soft rotis and bread.",
        category: "Grains",
        price: 4.50,
        farmer_id: "farmer_mock_3",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_7/400/300",
    },
    {
        id: "prod_8",
        name: "Fresh Potatoes",
        description: "Versatile and starchy potatoes, a staple for countless delicious dishes.",
        category: "Vegetables",
        price: 1.50,
        farmer_id: "farmer_mock_4",
        status: "Listed",
        image_url: "https://picsum.photos/seed/prod_8/400/300",
    },
];
